### ISSUE TITLE
Dialogs too big for the screen

### ISSUE THREAD

**Issue by pydoh** [silnrsi/libreoffice-linguistic-tools#13]
I'm having a problem with the tools dialogs being too big for the screen, I can't see the buttons at the bottom of the dialog. The only way that I can use the tools is by guessing how many tabs will get me to the OK or Cancel buttons. I'm using Fedora Linux with a 15.6", 16:9, 1366X768, and LibreOffice, if that's important.

I'm also having a problem with LibreOffice crashing when I do spellcheck, but maybe that's another issue. Thanks for listening.

**Comment by jkornelsen** [comment]
Which dialogs are you using?

It is actually not difficult to resize the dialogs.  To do this, go to Tools -> Macros -> Organize Dialogs.  Under LingToolsBasic, select the dialog to resize and press Edit.  Now drag the window until it is resized and then save.  Buttons and other elements can also be resized.

After you make changes, if this is something that may be a problem for others as well, then on the dialog edit screen, press Export Dialog, and then post the .xdl file here.  Keep in mind that on some systems it might become too small to read easily.

Yes, spellchecking is a different issue.  To discuss it, create a new issue and provide details.

**Comment by pydoh** [comment]
J. Kornelsen,

	I resized the dialog for WordListFile. I didn't change the size of the
widgets, just the spacing between the widgets. Then I resized the main
dialog window. It is a little bit smaller than it needs to be, but it is
entirely visible on screen now. I'm attaching the .dlg file, in case
anyone else wants to look at it.
	I think there was another dialog that was too small, I'll have to test
it to see which one. Thanks.

**Comment by jkornelsen** [comment]
Resized in 3a753c463f4589abdb803e9f847137e08965435d.
