### ISSUE TITLE
Cannot detect media-type

### ISSUE THREAD

**Issue by agricolamz** [silnrsi/libreoffice-linguistic-tools#19]
During the installation or removal I get this message:

![image](https://user-images.githubusercontent.com/15956515/88186356-bcc01e00-cc3d-11ea-8e13-544263ee4cde.png)

Version: 6.3.1.2
Build ID: b79626edf0065ac373bd1df5c28bd630b4424273
CPU threads: 8; OS: Linux 5.4; UI render: default; VCL: gtk3; 
Locale: en-US (en_US.UTF-8); UI-Language: en-US
Calc: threaded

**Comment by jkornelsen** [comment]
It sounds like your profile is corrupted, which often occurs when installing or uninstalling extensions. Delete that directory or perhaps the entire LO user profile directory (`$HOME/.config/libreoffice/4/user`) and then try again.

https://ask.libreoffice.org/en/question/33509/cannot-uninstall-extension-in-linux/

**Comment by agricolamz** [comment]
@jkornelsen, thank you, it helped!
