### ISSUE TITLE
Linguistic Tools causes LibreOffice to crash on ARM

### ISSUE THREAD

**Issue by livingfield** [silnrsi/libreoffice-linguistic-tools#22]
While running in Parallels Desktop VM on a MacBook M2:

This config causes LibreOffice to crash at the splash screen
Windows 11 24H2 for Arm
LibreOffice 24.2.4.2 **AARCH64** -- installed with the command:
`winget install TheDocumentFoundation.LibreOffice`

This config works OK:
Windows 11 23H2 for Arm, 
LibreOffice 24.2.4.2 x86_64 -- installed by downloading from libreoffice.org website)

**Comment by livingfield** [comment]
It is possible to use winget to install LibreOffice if one specifies the x64 architecture using either -a or --architecture in the winget install command. Presumably this would also work fine.
`winget install TheDocumentFoundation.LibreOffice -a X64`

**Comment by jkornelsen** [comment]
It sounds like you figured out the solution, so I'm closing this issue.
