### ISSUE TITLE
Interlinear Word Glosses

### ISSUE THREAD

**Issue by jkornelsen** [silnrsi/libreoffice-linguistic-tools#24]
User request to WSTech: "I would also like to request that a feature be added to the interlinear settings page so that I can add word glosses to my interlinear examples."

**Comment by LornaSIL** [comment]
Is this a WSTech thing? If so, who would that be?

**Comment by DavidLRowe** [comment]
Are we talking about the "Interlinear Settings" dialog in LibreOffice Writer with the Linguistic Tools addon (Linguistics > Interlinear Settings)? I've never used that feature, but it seems to be getting data from "interlinear XML files" generated by Flex or Toolbox. 

@jkornelsen Do you have any way to get more details on the request. I'm struggling to see how WSTech would be involved.

**Comment by LHayashi** [comment]
There are a number of language revitalization projects that are using FieldWorks. Some folks are using the Open Office Tools to easily distribute the transcribed texts. In the lg. revitalization context, often times the morpheme glosses are too linguisticky for language learning purposes, or the morpheme glosses need to be accompanied by word glosses to better understand the morpheme glosses. I was wondering if there might be a way, or a plan, to include a word gloss line in the libreoffice-linguistic-tools import from flextexts. Something like this: (the yellow highlights are manually added glosses into Libre Office)
![wordGloss](https://github.com/user-attachments/assets/2f49ad22-d6d8-4afc-8593-350131b96ef3)

I would also use this feature in our Field Methods instruction.

**Comment by jkornelsen** [comment]
@LHayashi: Sounds like a good idea, and it shouldn't be hard to add. By the way, Apache OpenOffice is badly out of date — there is concern about the infrequency of security updates and no new features in years. LibreOffice is strongly recommended instead. Sadly, a lot of people aren't aware of this — I'll write a note in the LOLT documentation.

Regarding WSTech's involvement, James Post forwarded the request to me. Once we resolve this issue, I'll send him an update.

**Comment by LHayashi** [comment]
Sounds good. I thought the request may have come from some of the Lg Revitalization work here. Sounds like it is a popular request!

**Comment by jkornelsen** [comment]
A new version that supports word gloss lines, [v4.1](https://github.com/silnrsi/libreoffice-linguistic-tools/releases/tag/v4.1), has now been released.
